### ISSUE TITLE
Favicon of Home page is not working

### ISSUE THREAD

**Issue by gupta-piyush19** [Aakansha99/Github-Profile-Analyser#16]
i would like to work on this issue and will use some other favicon as well.

**Comment by Aakansha99** [comment]
Okay sure @gupta-piyush19 . You can work on this issue.

**Comment by ag278** [comment]
@gupta-piyush19 @Aakansha99  I want like to contribute on this issue. Please allow me to do this.

**Comment by Aakansha99** [comment]
@ag278 it is already assigned to @gupta-piyush19. Please find some unassigned issue
