### ISSUE TITLE
Git compare table.

### ISSUE THREAD

**Issue by Sapna2001** [Aakansha99/Github-Profile-Analyser#25]
Add margin between the table in git compare margin.

Screenshots
Current form:
![real](https://user-images.githubusercontent.com/56690856/90330187-79e93000-dfc8-11ea-95ac-ed4667290414.png)

Modification:
![Annotation 2020-08-16 135448](https://user-images.githubusercontent.com/56690856/90330192-7fdf1100-dfc8-11ea-8995-812d8f0f71f6.png)

**Comment by Sapna2001** [comment]
@Aakansha99  please assign me this issue.

**Comment by Aakansha99** [comment]
@Sapna2001  this issue is assigned to you
