### ISSUE TITLE
Background of Home page

### ISSUE THREAD

**Issue by varunvj1** [Aakansha99/Github-Profile-Analyser#37]
**Description of the enhancement**
The background of the home page seems a bit empty even with dark mode functionality. I can add cool animation to the background which will make it look more elegant and stylish.

**Screenshots**

**NOTE**
- The background has **animation**. So its a **moving animated design**.

![Dark-mode](https://user-images.githubusercontent.com/52121657/90566464-26dccc00-e1c6-11ea-80c6-030854cdd0f7.png)
![Light-mode](https://user-images.githubusercontent.com/52121657/90566467-28a68f80-e1c6-11ea-9a3c-fbdaf4930323.png)

**Comment by varunvj1** [comment]
Please assign this to me.

**Comment by Mitali-laroia** [comment]
I want to work on this issue.

**Comment by Aakansha99** [comment]
@varunvj1 this issue is assigned to you. You can continue with the work.

**Comment by varunvj1** [comment]
I've resolved the conflicts. Please review my PR @Aakansha99
