### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by goelradhika** [Aakansha99/Github-Profile-Analyser#38]

**Comment by Mitali-laroia** [comment]
Can you describe in which specific elements the page are not responsive and I would like to work on this issue.

**Comment by goelradhika** [comment]
This is how the site looks like.

![Screenshot (42)](https://user-images.githubusercontent.com/48651839/90628610-c3a56680-e1d2-11ea-91ed-bcbf1fd8ecc8.png)

**Comment by ymaheshwari1** [comment]
I am also interested in working on this.

**Comment by Aakansha99** [comment]
@Mitali-laroia this issue is assigned to you. You can continue with the work.

**Comment by devanshi-katyal** [comment]
i would like to work on this issue
