### ISSUE TITLE
Icons in the main page

### ISSUE THREAD

**Issue by Sapna2001** [Aakansha99/Github-Profile-Analyser#44]
**Description of the enhancement**
Icons on the main page aren't much visible.

**Screenshots**
Current View:
![Annotation 2020-08-21 091708](https://user-images.githubusercontent.com/56690856/90850572-ac5fa800-e38f-11ea-8eb0-c10feb975f1d.png)

Modification:
![Annotation 2020-08-21 091833](https://user-images.githubusercontent.com/56690856/90850585-b5e91000-e38f-11ea-9b37-c52bba16ba04.png)

@Aakansha99  please assign me this issue.

**Comment by Aakansha99** [comment]
okay @Sapna2001  this issue is assigned to you
