### ISSUE TITLE
Background improvement

### ISSUE THREAD

**Issue by dipanshparmar** [Aakansha99/Github-Profile-Analyser#46]
Hey Aakansha,
I think the current background is too dark for all the text and logos to shine up. I will add true rich colors linear gradient in the background for good contrast so that the words and icons are clearly visible.

![image](https://user-images.githubusercontent.com/49204837/90961433-a6201780-e4c6-11ea-94bd-6d62cfa7c150.png)

**Comment by tejan-singh** [comment]
can I work on this issue ?

**Comment by Mitali-laroia** [comment]
I would like to work on this issue.

**Comment by Aakansha99** [comment]
@devanshiv123 this issue is assigned to you. Go ahead with it

**Comment by devanshiv123** [comment]
> @devanshiv123 this issue is assigned to you. Go ahead with it

@Aakansha99 I think you mentioned me by mistake. @dipanshparmar had opened the issue and wanted to get it assigned.

**Comment by Aakansha99** [comment]
Yeah sorry its assigned to @dipanshparmar
