### ISSUE TITLE
Decrease landing page to single page without scrollbar

### ISSUE THREAD

**Issue by God-father1** [Aakansha99/Github-Profile-Analyser#54]
**Adjust index.html such that the scrollbar disappears**
When we load the app, the scrollbar also appears your work is to remove it by fixing the page size and icon size.

- [ ] Add comments to your code.

- [ ] Decrease fav icon size.

- [ ] Fix size of paragraph containing coding thought.

- [ ] Fix footer to bottom of screen.

**Screenshots**
![Screenshot (125)_LI](https://user-images.githubusercontent.com/58758331/91628704-1f949a00-e9e0-11ea-9ee9-69abc5daf9b7.jpg)

**Comment by Aakansha99** [comment]
@God-father1 would you like to work on this issue?

**Comment by God-father1** [comment]
@Aakansha99  Let's wait for someone to work on this, if no one works on it then I'll work on it.

**Comment by kritikaparmar-programmer** [comment]
@Aakansha99  and @God-father1 , I would like to work on this issue

**Comment by God-father1** [comment]
You will not be assigned the issue, first PR for the issue will be accepted.

**Comment by kritikaparmar-programmer** [comment]
Hey @God-father1 , there is already too much on the index/home page , how to reduce it
There are many things which were not When you opened the issue
Please explain the issue to me.. I want to contribute to this issue..
