### ISSUE TITLE
Fix background of index.html

### ISSUE THREAD

**Issue by God-father1** [Aakansha99/Github-Profile-Analyser#55]
**Fixing background of index.html**

Currently, the background is not fixed and repeating when we decrease the size of the screen. 
<hr>

***Solution and Expected behavior***

Your work is to fix the background and make is no-repeat using CSS background properties.

- [ ] Change background attachment.

- [ ] Change background repeat.

- [ ] Change background size.

- [ ]  Add comments to your code.
<hr>

**Screenshots**

*Before*

![Screenshot (126)](https://user-images.githubusercontent.com/58758331/91629075-3ab4d900-e9e3-11ea-80c2-a7b3412d13ba.png)

*After*

![Screenshot (127)](https://user-images.githubusercontent.com/58758331/91629083-4accb880-e9e3-11ea-9ed4-51d0a04cc532.png)

**Comment by Mitali-laroia** [comment]
I would like to work on this issue.

**Comment by Aakansha99** [comment]
@God-father1 would you like to work on this issue?

**Comment by God-father1** [comment]
> I would like to work on this issue.

Yes, @Mitali-laroia, you can but the issue will be assigned to you when you attach PR.

**Comment by God-father1** [comment]
> @God-father1 would you like to work on this issue?

No @Aakansha99, Let participants handle this.

**Comment by kritikaparmar-programmer** [comment]
I would like to work on this issue @God-father1 and @Aakansha99 ..

**Comment by God-father1** [comment]
You will not be assigned the issue, first PR for the issue will be accepted.
