### ISSUE TITLE
The Project requires some clear contributing guidelines in either README.md or a separate CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Git-Harshit** [Aakansha99/Github-Profile-Analyser#56]
**Description of the enhancement**
The project seems a good to go tool to analyse GitHub profiles, all thanks to the GitHub API. However, without any statement of code, and scope of collaboration from the moderators and collaborators end, it'd be difficult for new contributors to start contributing to this project. Therefore, I request the repo owner(s) to begin with a [_contributing.md_ file](https://github.com/Aakansha99/Github-Profile-Analyser/new/master), or allow any other to atleast begin with a basic idea of the procedure to begin contributing. 

Please also consider adding relevant tags to this issue like CH20, documentation, etc. for contributors to be able to get a proper credit for their work. 

Let this issue be open for CONTRIBUTING content curation and further improvements.

**Comment by Aakansha99** [comment]
Yeah this sounds great. So would you like to work on this issue?

**Comment by Git-Harshit** [comment]
Sure @Aakansha99, I'd love to! 😄 
I'm planning to initiate a CONTRIBUTION.md or CONTRIBUTING.md file (whichever name sounds better), and then it could be further reviewed and updated as and when needed.

**Comment by Aakansha99** [comment]
Yeah okay. This issue is assigned to you. Go ahead with it
