### ISSUE TITLE
The current theme needs visual tweaks and enhancements for a clearer and better interface.

### ISSUE THREAD

**Issue by Git-Harshit** [Aakansha99/Github-Profile-Analyser#57]
**Description of the enhancement**
The current public version of website lacks clear view, specially in light (non-dark) mode. Also, certain contents in the [hosted site](https://aakansha99.github.io/Github-Profile-Analyser/) (as on 1st September, 2020) can be more better distinguishable. 

**Screenshots**
Here's a pic to how it currently looks.
![Capture_Unclear](https://user-images.githubusercontent.com/57865187/91878284-b1303000-ec9c-11ea-8689-cea7b8dd001c.PNG)

As you can see, the user needs to have increased screen brightness and a very clear vision in order to actually see the entire directory at ease. 

So, I hope to see this getting fixed as soon as possible.

**Comment by Git-Harshit** [comment]
@Aakansha99 Please allow me to work on this. 
I'll try my best to enhance the page styling, without any replacements and such additional changes, using CSS.

Also, please do a favor by adding CH20, enhancement and any other label that you feel would be relevent for this issue.

**Comment by Aakansha99** [comment]
Okay @Git-Harshit. This issue is assigned to you
