### ISSUE TITLE
Suggest a name and add logo to it

### ISSUE THREAD

**Issue by Aakansha99** [Aakansha99/Github-Profile-Analyser#6]

**Comment by gupta-piyush19** [comment]
@Aakansha99 i would like to work on this issue, i can provide some good name and logo for the web app, please allow me to do work on it

**Comment by Aakansha99** [comment]
This issue is open for all. Anyone can submit a PR for this.

**Comment by Ayushi841** [comment]
@Aakansha99 i want to do this project d, i think I'm creative and i can provide a good logo

**Comment by Aakansha99** [comment]
Sure @Ayushi841, go ahead with it.

**Comment by ag278** [comment]
I would like to work on this issue, please allow me to work on it

**Comment by chetnaSharma24** [comment]
@Aakansha99  i would like to work upon this issue.
may I design the logo??

**Comment by chetnaSharma24** [comment]
Heyy @Aakansha99  , could you please assign this to me. I wanted to design the logo
