### ISSUE TITLE
Background enhancement of index.html

### ISSUE THREAD

**Issue by varunvj1** [Aakansha99/Github-Profile-Analyser#62]
**Description of the enhancement**
As requested, I have improved the background by adding more animations.
<br>

**Screenshots**
#### Current Background
![Before](https://user-images.githubusercontent.com/52121657/92156814-27709600-ee47-11ea-9b32-a897650ac83b.png)
<br>

#### New Enhanced Background
The background has <b> animations and transitions </b>
![After](https://user-images.githubusercontent.com/52121657/92157164-acf44600-ee47-11ea-8b12-d0a389ef2ca2.png)

**Comment by varunvj1** [comment]
@Aakansha99 I've created a PR for the same. Please review and let me know if there are some changes that needs to be made.

**Comment by Adyasha8105** [comment]
@Aakansha99 I want to work on this issue
