### ISSUE TITLE
Revamping the navigation bar

### ISSUE THREAD

**Issue by sameersrivastava13** [Aakansha99/Github-Profile-Analyser#65]
**Describe the bug**
Currently the navigation bar is not fixed properly and when the site is viewed on smaller screens it gets split as shown below in the screenshot.

**Expected behavior**
I would like to revamp the navigation bar by adding a responsive navigation bar so that when user will resize the browser window or will try to access the site on smaller screen he should be able to navigate or i can say the navigation bar should work properly.

**Screenshots**

![Screenshot (101)](https://user-images.githubusercontent.com/56088741/92243478-2ee37e00-eedf-11ea-9d58-740d5429b479.png)

**Comment by sameersrivastava13** [comment]
@Aakansha99 Please assign me this issue.

**Comment by Mitali-laroia** [comment]
@Aakansha99  I would like to work on this issue.

**Comment by Aakansha99** [comment]
Okay @sameersrivastava13  this issue is assigned to you
