### ISSUE TITLE
Home page bug

### ISSUE THREAD

**Issue by varunvj1** [Aakansha99/Github-Profile-Analyser#77]
**Describe the bug**
The home page is all messed up

**Expected behavior**
It should show only one navbar, one footer, but it is showing double.

**Screenshots**
![bug](https://user-images.githubusercontent.com/52121657/92988654-0cf38800-f4eb-11ea-81a7-1ddaf96d58ba.png)

**Comment by varunvj1** [comment]
Please assign this to me @Aakansha99

**Comment by kritikaparmar-programmer** [comment]
Hey @varunvj1 I've already made a PR for a similar kind of issue..

**Comment by Aakansha99** [comment]
This is already resolved.
