### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by sameersrivastava13** [Aakansha99/Github-Profile-Analyser#79]
**Description of the enhancement**
To add a 404 error page to keep a visitor on your site even if he/she hits a page that doesn't exist. Also to change the bad User experience to a positive one by adding some links to that 404 page so that the visitor can navigate to some other page.

**Comment by sameersrivastava13** [comment]
@Aakansha99 Please assign me the issue.

**Comment by Aakansha99** [comment]
Okay @sameersrivastava13 this issue is assigned to you
