### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by varunvj1** [Aakansha99/Github-Profile-Analyser#8]
The navigation bar could be styled more

**Comment by varunvj1** [comment]
Please assign this to me

**Comment by Aakansha99** [comment]
Okay @varunvj1. Go ahead with the issue

**Comment by Mitali-laroia** [comment]
Can I work on this issue?

**Comment by Kaushkiraj** [comment]
I want to work on this issue.  @Aakansha99 can you please assign to me?

**Comment by subh1503** [comment]
I want to work on this issue @Aakansha99

**Comment by varunvj1** [comment]
Hey @Aakansha99 please review my PR
