### ISSUE TITLE
New Navbar present only on the index page

### ISSUE THREAD

**Issue by gupta-piyush19** [Aakansha99/Github-Profile-Analyser#85]
**Description of the enhancement**
Current Index page Navbar should be present on all the pages of the website.

**Comment by gupta-piyush19** [comment]
I would like to add that navbar to all the pages and also refactor the navbar code which will avoid copying large code on every page.

**Comment by Aakansha99** [comment]
okay @gupta-piyush19 this issue is assigned to you
