### ISSUE TITLE
Page  pre-loader

### ISSUE THREAD

**Issue by varunvj1** [Aakansha99/Github-Profile-Analyser#87]
**Describe the bug**
Page pre-loader on index.html is not working

**Screenshots**
![Bug](https://user-images.githubusercontent.com/52121657/93932069-42933f00-fd3d-11ea-88fa-4cc4a3202da4.png)

**Comment by varunvj1** [comment]
@Aakansha99 please assign it to me.

**Comment by Aakansha99** [comment]
okay @varunvj1 this issue is assigned to you

**Comment by varunvj1** [comment]
@Aakansha99  please add the required labels like CH20 as well.
